export class Profession {
    constructor(
       
//  Dashboard model variables
        public contactNo?: number,
        public firstName?: string,
        public middleName?: string,
        public lastName?: string,
        public mandalId?: number,
        public mandalName?: string,
        public mandaltype?: string,
        public relationship?: string,
        public index?: number,
        public familyId?:number,
        public address?: string,
        public city?: string,
        public pincode?: number,
        public area?: string,
        public kshetra?:string,
        public education?: string,
        public profession?: string,
        public occupation?: string,
        public businessType?: string,
        public skill?: string,
        public workInfo?: string,
        public status?:number,
        public email?: string,
        public bloodGroup?: string,
        public dob?: string,
        public gender?: string,
        public marritalStatus?: string,
        public isForeignCountry?: string,
        public foreignCountry?: string,
        public foreignCity?: string,
        public foreignContact?: string,
    ){}
}